apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-backend
spec:
  selector:
    matchLabels:
      app: hms-backend
  template:
    metadata:
      labels:
        app: hms-backend
    spec:
      containers:
      - name: hms-backend
        image: oadrianoo/hms-backend:{{ .Values.container.image.version }}
        ports:
        - containerPort: {{ .Values.container.port }}
        env:
        - name: PORT
          value: {{ .Values.env.PORT }}
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: hms-config
              key: NODE_ENV
        - name: CLOUD_USER
          valueFrom:
            secretKeyRef:
              name: hms-secret
              key: CLOUD_USER
        - name: CLOUD_PWD
          valueFrom:
            secretKeyRef:
              name: hms-secret
              key: CLOUD_PWD
        - name: CLOUD_DB
          valueFrom:
            secretKeyRef:
              name: hms-secret
              key: CLOUD_DB
        - name: HASH_PASS
          valueFrom:
            secretKeyRef:
              name: hms-secret
              key: HASH_PASS