apiVersion: v1
kind: Service
metadata:
  name: hms-backend
spec:
  type: NodePort
  selector:
    app: hms-backend
  ports:
    - protocol: TCP
      port: {{ .Values.container.port}}
      targetPort: {{ .Values.container.port}}
      nodePort: {{ .Values.service.nodePort }}