---
apiVersion: v1
kind: Secret
metadata:
  name: hms-secret
  namespace: staging
type: Opaque
data:
  CLOUD_DB: aG1zX2h1Yg==
  CLOUD_PWD: Y2xhcmluaGE0MTE4
  CLOUD_USER: QWRyaWFubw==
  HASH_PASS: aG1zX2h1Yg==  
---
apiVersion: v1
kind: Secret
metadata:
  name: hms-secret
  namespace: production
type: Opaque
data:
  CLOUD_DB: aG1zX2h1Yg==
  CLOUD_PWD: Y2xhcmluaGE0MTE4
  CLOUD_USER: QWRyaWFubw==
  HASH_PASS: aG1zX2h1Yg==
---