apiVersion: v1
kind: Service 
metadata:
  name: hms-frontend
spec:
  type: NodePort
  selector:
    app: hms-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30030 
