apiVersion: v1
kind: Deployment
metadata:
  name: hms-frontend
spec:
  selector:
    matchLabels:
      app: hms-frontend
  template:
    metadata:
      labels:
        app: hms-frontend
    spec:
      containers:
      - name: hms-frontend
        image: oadrianoo/hms-frontend:beta
        ports:
        - containerPort: 80
