---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hms-config
  namespace: staging
data:
  NODE_ENV: staging     
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hms-config
  namespace: production
data:
  NODE_ENV: production  
---