apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hms-backend-full.fullname" . }}
  labels:
    {{- include "hms-backend-full.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hms-backend-full.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hms-backend-full.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hms-backend-full.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: PORT
            value: {{ .Values.env.PORT }}
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: hms-config
                key: NODE_ENV
          - name: CLOUD_USER
            valueFrom:
              secretKeyRef:
                name: hms-secret
                key: CLOUD_USER
          - name: CLOUD_PWD
            valueFrom:
              secretKeyRef:
                name: hms-secret
                key: CLOUD_PWD
          - name: CLOUD_DB
            valueFrom:
              secretKeyRef:
                name: hms-secret
                key: CLOUD_DB
          - name: HASH_PASS
            valueFrom:
              secretKeyRef:
                name: hms-secret
                key: HASH_PASS    
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
