apiVersion: v1
kind: Service 
metadata:
  name: hms-frontend
spec:
  type: NodePort
  selector:
    app: hms-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
      nodePort: {{ .Values.service.nodePort }} 
